---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 3

- name: Make sure the gnupg and apt-transport-https packages are present
  ansible.builtin.apt:
    pkg:
      - acl
    state: present
  register: apt_status
  until: apt_status is success
  delay: 5
  retries: 3
